import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="caramellatte"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Image src={"/images/logo.png"} alt="Logo UTI" width={320} height={60} priority></Image>
        <header>
        </header>
        <main className="p-3">

        {children}
        </main>
        <footer>
          Copyright &copy; 2025 - IF22DX
        </footer>
      </body>
    </html>
  );
}
